apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: quarkus-demo

type: Opaque

stringData:

  # PostgreSQL
  POSTGRES_DB: personasdb
  POSTGRES_USER: quarkus
  POSTGRES_PASSWORD: quarkus123

  # Quarkus
  QUARKUS_DATASOURCE_USERNAME: quarkus
  QUARKUS_DATASOURCE_PASSWORD: quarkus123
