apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: quarkus
  namespace: monitoring

  labels:
    release: monitoring

spec:

  selector:
    matchLabels:
      app: quarkus

  namespaceSelector:
    matchNames:
      - quarkus-demo

  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
