{{- if and .Values.monitoring.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: quarkus
  namespace: {{ .Release.Namespace }}

  labels:
    release: {{ .Values.monitoring.release }}

spec:

  selector:
    matchLabels:
      app: quarkus

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  endpoints:
    - port: {{ .Values.monitoring.port }}
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}

{{- end }}