{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: quarkus
  namespace: {{ .Values.monitoring.namespace }}

  labels:
    release: {{ .Values.monitoring.release }}

spec:

  selector:

    matchLabels:
      app: quarkus

  namespaceSelector:

    matchNames:
      - {{ .Release.Namespace }}

  endpoints:

    - port: {{ .Values.monitoring.port }}

      path: {{ .Values.monitoring.path }}

      interval: {{ .Values.monitoring.interval }}

{{- end }}