apiVersion: v1
kind: Service

metadata:
  name: quarkus
  namespace: {{ .Release.Namespace }}

spec:

  selector:
    app: quarkus

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080

  type: {{ .Values.service.type }}