name: Build, Test & Publish

on:
  push:
    branches:
      - master
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build
        run: ./mvnw clean verify

      - name: Build and Push Docker image
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ./mvnw package \
            -DskipTests \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=docker.io \
            -Dquarkus.container-image.group=chrisqhapaq \
            -Dquarkus.container-image.name=quarkus-k8s-demo \
            -Dquarkus.container-image.tag=${{ github.sha }}
